# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\"3\n\x15TemperatureSetRequest\x12\x1a\n\x12\x64\x65siredTemperature\x18\x01 \x01(\x02\"4\n\x16TemperatureSetResponse\x12\x1a\n\x12\x64\x65siredTemperature\x18\x01 \x01(\x02\"\x17\n\x15GetTemperatureRequest\"-\n\x16GetTemperatureResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x32\xa3\x01\n\x15TemperatureController\x12\x43\n\x0eSetTemperature\x12\x16.TemperatureSetRequest\x1a\x17.TemperatureSetResponse\"\x00\x12\x45\n\x0eGetTemperature\x12\x16.GetTemperatureRequest\x1a\x17.GetTemperatureResponse\"\x00\x30\x01\x62\x06proto3')
)




_TEMPERATURESETREQUEST = _descriptor.Descriptor(
  name='TemperatureSetRequest',
  full_name='TemperatureSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='desiredTemperature', full_name='TemperatureSetRequest.desiredTemperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=68,
)


_TEMPERATURESETRESPONSE = _descriptor.Descriptor(
  name='TemperatureSetResponse',
  full_name='TemperatureSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='desiredTemperature', full_name='TemperatureSetResponse.desiredTemperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=122,
)


_GETTEMPERATUREREQUEST = _descriptor.Descriptor(
  name='GetTemperatureRequest',
  full_name='GetTemperatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=147,
)


_GETTEMPERATURERESPONSE = _descriptor.Descriptor(
  name='GetTemperatureResponse',
  full_name='GetTemperatureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='GetTemperatureResponse.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=194,
)

DESCRIPTOR.message_types_by_name['TemperatureSetRequest'] = _TEMPERATURESETREQUEST
DESCRIPTOR.message_types_by_name['TemperatureSetResponse'] = _TEMPERATURESETRESPONSE
DESCRIPTOR.message_types_by_name['GetTemperatureRequest'] = _GETTEMPERATUREREQUEST
DESCRIPTOR.message_types_by_name['GetTemperatureResponse'] = _GETTEMPERATURERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperatureSetRequest = _reflection.GeneratedProtocolMessageType('TemperatureSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATURESETREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureSetRequest)
  ))
_sym_db.RegisterMessage(TemperatureSetRequest)

TemperatureSetResponse = _reflection.GeneratedProtocolMessageType('TemperatureSetResponse', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATURESETRESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureSetResponse)
  ))
_sym_db.RegisterMessage(TemperatureSetResponse)

GetTemperatureRequest = _reflection.GeneratedProtocolMessageType('GetTemperatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTEMPERATUREREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:GetTemperatureRequest)
  ))
_sym_db.RegisterMessage(GetTemperatureRequest)

GetTemperatureResponse = _reflection.GeneratedProtocolMessageType('GetTemperatureResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETTEMPERATURERESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:GetTemperatureResponse)
  ))
_sym_db.RegisterMessage(GetTemperatureResponse)



_TEMPERATURECONTROLLER = _descriptor.ServiceDescriptor(
  name='TemperatureController',
  full_name='TemperatureController',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=197,
  serialized_end=360,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetTemperature',
    full_name='TemperatureController.SetTemperature',
    index=0,
    containing_service=None,
    input_type=_TEMPERATURESETREQUEST,
    output_type=_TEMPERATURESETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTemperature',
    full_name='TemperatureController.GetTemperature',
    index=1,
    containing_service=None,
    input_type=_GETTEMPERATUREREQUEST,
    output_type=_GETTEMPERATURERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATURECONTROLLER)

DESCRIPTOR.services_by_name['TemperatureController'] = _TEMPERATURECONTROLLER

# @@protoc_insertion_point(module_scope)
